name: Update Progress & README

# allow the workflow to push changes using the GITHUB_TOKEN
permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.ACTIONS_PAT }}   # use PAT when GITHUB_TOKEN cannot push

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Normalize progress.json
        run: node .github/scripts/updateProgress.js

      - name: Generate README
        run: node .github/scripts/generateReadme.js

      - name: Commit & push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add progress.json README.md || true
          if ! git diff --staged --quiet; then
            git commit -m "chore(ci): auto-update progress and README" || echo "commit failed"
            git push
          else
            echo "No changes to commit"
          fi
