name: Update Progress

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Update progress
        run: node $GITHUB_WORKSPACE/.github/scripts/updateProgress.js
      - name: Commit changes
        run: |
          git config user.name "noorearafin"
          git config user.email "noorearafin@gmail.com"
          git add progress.json
          git commit -m "✅ Auto update progress"
          git push
